[project]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Tutorial: Run an ONNX model with Python"
name = "max-onnx-resnet"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[dependencies]
max = ">=24.4.0,<25"
numpy = "<2.0"

[pypi-dependencies]
datasets = "==2.18"
onnx = "==1.16.0"
pillow = "==10.3.0"
torch = "==2.2.2"
transformers = "==4.40.1"
