[project]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "Tutorial: Run an ONNX model with Python"
name = "max-onnx-resnet"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
test = "python3 download-model.py && python3 run.py"

[dependencies]
python = ">=3.9,<3.13"
max = ">=24.5.0a,<24.6"
numpy = "<2.0"
pytorch = ">=2.4.0,<3"
onnx = "==1.16.0"
transformers = "==4.40.1"
datasets = "==2.18"

[pypi-dependencies]
pillow = "==10.3.0"
python-dateutil = "==2.9.0"
