[project]
name = "MAX"
requires-python = ">=3.9,<3.13"

[tool.black]
include = '\.pyi?$'
line-length = 80
preview = true
fast = true

[tool.pyright]
typeCheckingMode = "off"
reportMissingImports = false
