[project]
name = "BERT C Torchscript"
version = "1.0.0"
description = "MAX Examples"
authors = ["Modular <hello@modular.com>"]
channels = ["pytorch", "conda-forge", "https://conda.modular.com/max-nightly"]
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]

[dependencies]
python = ">=3.9,<3.13"
max = "*"
numpy = "<2.0"
networkx = "==3.1"
pytorch = "==2.4"
transformers = ">=4.44.2,<5"
