[project]
platforms = ["osx-arm64", "linux-64"]
version = "0.0.0"
authors = ["Modular <hello@modular.com>"]
channels = ["pytorch", "conda-forge", "https://conda.modular.com/max-nightly/"]
description = "Add a short description here"
name = "local"

[tasks]

[dependencies]
max = "24.6.0.dev2024111816"
pytorch = ">=2.4.1,<3"
