[project]
platforms = ["osx-arm64", "linux-64"]
version = "0.0.0"

[tasks]

[dependencies]
max = ">=24.4.0,<25"
pytorch = ">=2.4.1,<3"
authors = ["Modular <hello@modular.com>"]
channels = ["pytorch", "conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "local"
