[project]
name = "gui"
version = "1.0.0"
channels = ["conda-forge", "https://conda.cloudsmith.io/modular/max-nightly/"]
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]

[dependencies]
max = "*"
numpy = "==1.26.4"

[pypi-dependencies]
accelerate = "==0.33.0"
chromadb = "==0.5.5"
diffusers = "==0.30.1"
docx2txt = "==0.8"
EbookLib = "==0.18"
fastembed = "==0.3.6"
ftfy = "==6.2.3"
html2text = "==2024.2.26"
ipython = "==8.26.0"
llama-index = "==0.11.2"
nbconvert = "==7.16.4"
networkx = "==3.3"
onnxruntime = "==1.19"
onnxslim = "==0.1.32"
openai = "==1.42.0"
opencv-python = ">=4.10"
optimum = { extras = ["onnxruntime"], version = "==1.21.4" }
pillow = "==10.4.0"
protobuf = "==3.20.3"
psutil = "==6.0.0"
streamlit = "==1.38.0"
streamlit-webrtc = "==0.47.7"
torch = "==2.4.0"
transformers = "==4.43.4"
ultralytics = "==8.2.83"
watchdog = "==4.0.0"

[tasks]
gui = "streamlit run home.py"
