[project]
name = "Stable Diffusion Mojo Onnx"
version = "1.0.0"
description = "MAX Examples"
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "anaconda", "https://conda.cloudsmith.io/modular/max-nightly/"]
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]

[dependencies]
python = ">=3.9,<3.13"
max = "*"
pip = ">=24.0,<25"
