[project]
name = "Mistral7b Python Onnx"
version = "1.0.0"
description = "MAX Examples"
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/", "pytorch"]
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]

[dependencies]
python = ">=3.9,<3.13"
max = "24.6.0.dev2024111816"
networkx = "3.1"
transformers = ">=4.44.0"
numpy = "<2.0"
huggingface_hub = ">=0.24.6,<0.25"
onnx = "==1.16.0"
onnxruntime = "==1.17.3"

[pypi-dependencies]
optimum = ">=1.19.1"

# For performance, prefer pytorch over anything else.
# The linux ARM package doesn't exist there, so prefer PyPi instead. 
[target.linux-64.dependencies]
pytorch = {version = "==2.4.1", channel = "pytorch"}
[target.osx-arm64.dependencies]
pytorch = {version = "==2.4.1", channel = "pytorch"}
[target.linux-aarch64.pypi-dependencies]
torch = "==2.4.1"
[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cpu"]
