##===----------------------------------------------------------------------===##
#
# This file is Modular Inc proprietary.
#
##===----------------------------------------------------------------------===##
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "max.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "max.name" . }}
    helm.sh/chart: {{ template "max.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
    {{- if .Values.envSecret }}
    {{- range $key, $value := .Values.envSecret }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
