[project]
name = "Mojo Graph API Examples"
version = "1.0.0"
description = "MAX Examples"
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]

[tasks]
llama2 = "mojo run_pipeline.🔥 llama2"
llama3 = "mojo run_pipeline.🔥 llama3"
replit = "mojo run_pipeline.🔥 replit"
quantize-tinystories = "mojo run_pipeline.🔥 quantize-tinystories"
basic = "mojo basics/basic.🔥"
inspect-guff = "mojo inspect-guff.🔥"

[dependencies]
python = ">=3.9,<3.13"
huggingface_hub = ">=0.24.6,<0.25"
transformers = ">=4.44.2"
max = "24.6.0.dev2024121016"
